#!/usr/bin/env node
const fs=require('fs'),path=require('path'),{execSync}=require('child_process');
const Database=require('better-sqlite3');
const db=new Database(path.join(__dirname,'satfocus-blog.db'));
const outputDir=path.join(__dirname,'output');
fs.mkdirSync(outputDir,{recursive:true});
const args=process.argv.slice(2);
const REWRITE=args.includes('--rewrite');
let apiKey=process.env.ANTHROPIC_API_KEY||'';
if(!apiKey){try{const e=execSync('pm2 env 1 2>/dev/null').toString();const m=e.match(/ANTHROPIC_API_KEY:\s*(\S+)/);if(m)apiKey=m[1]}catch(e){}}
const S={url:'https://www.satfocussecurity.co.uk',phone:'0208 422 7918',email:'info@satfocussecurity.co.uk',logo:'https://www.satfocussecurity.co.uk/wp-content/uploads/2021/05/Satfocus-Logo-1024x350-1.png',checkatrade:'https://www.satfocussecurity.co.uk/wp-content/uploads/2019/12/check-a-trade-uk2.png',which:'https://www.satfocussecurity.co.uk/wp-content/uploads/elementor/thumbs/which-trusted-trader-uk-satfocus-qkv93dl84lig6nmro81hyla1avy3dmazay3nvhcuzs.png'};
const IL={cctv:S.url+'/service/cctv-installation-in-london/',hik_ahd:S.url+'/hikvision-hd-analog-cctv-packages/',hik_ip:S.url+'/hikvision-ip-cctv-packages/',alarms:S.url+'/service/burglar-alarm-installation-intruder-alarm-installation-in-london/',pyronix:S.url+'/pyronix-alarm-packages/',texecom:S.url+'/texecom-alarm-packages/',visonic:S.url+'/visonic-powermaster-alarms/',risco:S.url+'/risco-agility-alarm-packages/',upgrade:S.url+'/burglar-alarm-upgrade/',service:S.url+'/burglar-alarm-service/',intercom:S.url+'/gate-intercom-system/',services:S.url+'/services-home-security-systems-av-and-security-solutions/',locations:S.url+'/our-service-locations/',contact:S.url+'/contact/'};
function esc(t){return String(t||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;')}
function buildPrompt(topic){
const areas=['Harrow','Wembley','Ealing','Acton','Greenford','Ruislip','Pinner','Stanmore','Edgware','Finchley','Hendon','Hounslow','Uxbridge','Southall','Richmond','Chiswick','Hammersmith','Kensington','Kilburn','Willesden','Kingsbury'].sort(()=>Math.random()-.5).slice(0,5).join(', ');
return `You are an expert SEO content writer. Write for SatFocus Security Solutions (London security installer).

KEYWORD: "${topic.keyword}" | CATEGORY: ${topic.category}

AI-ERA SEO REQUIREMENTS:
1. DIRECT ANSWER: First 2-3 sentences must directly answer the implied question. AI systems extract this as featured snippet.
2. KEY TAKEAWAYS: After intro include: <div class="sf-takeaways"><h3>Key Takeaways</h3><ul><li>point</li></ul></div> with 4-5 points.
3. H2 HEADINGS as questions (People Also Ask style): "How much does X cost?" not "X Costs"
4. Each H2 section starts with 1-2 sentence direct answer before elaborating.
5. INTERNAL LINKS (use 4-6): CCTV: ${IL.cctv} | Alarms: ${IL.alarms} | Texecom: ${IL.texecom} | Pyronix: ${IL.pyronix} | Hikvision: ${IL.hik_ip} | Intercom: ${IL.intercom} | Alarm service: ${IL.service} | Alarm upgrade: ${IL.upgrade} | Contact: ${IL.contact} | Locations: ${IL.locations}
6. E-E-A-T: mention specific models (Texecom Premier Elite, Ajax Hub 2 Plus, Hikvision DS-2CD series, Paxton Net2), British Standards (BS EN 50131, BS 8418), UK law, Checkatrade & Which Trusted Trader approved.
7. Local areas: ${areas}
8. DO NOT mention NSI, physical address, or generic filler.
9. British English. 1,400-2,000 words. End with CTA + phone ${S.phone}
10. FAQ: 5 questions as people would type into Google.

JSON ONLY: {"title":"...(under 60 chars)","meta_description":"...(150-155 chars)","content":"...(HTML h2,h3,p,ul,li,a,div.sf-takeaways)","excerpt":"...(2-3 sentences)","word_count":1600,"faq":[{"question":"...","answer":"..."}]}`}

async function rewritePost(post){
if(!apiKey){console.log('No API key');return post}
const Anthropic=require('@anthropic-ai/sdk');
const anthropic=new Anthropic({apiKey});
console.log('  Rewriting:',post.keyword);
const r=await anthropic.messages.create({model:'claude-sonnet-4-20250514',max_tokens:4096,messages:[{role:'user',content:buildPrompt({keyword:post.keyword,category:post.category})}]});
const t=r.content[0].text;const p=JSON.parse(t.replace(/```json\s*/g,'').replace(/```\s*/g,'').trim());
const now=Math.floor(Date.now()/1000);
db.prepare('UPDATE sf_blog_posts SET title=?,meta_description=?,content=?,excerpt=?,word_count=?,updated_at=? WHERE id=?').run(p.title,p.meta_description,p.content,p.excerpt,p.word_count||1600,now,post.id);
return {...post,...p}}

const CSS=`*{margin:0;padding:0;box-sizing:border-box}:root{--r:#BC0000;--d:#1a1a1a;--t:#333;--l:#f7f7f7;--b:#e8e8e8}body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;color:var(--t);line-height:1.8;font-size:17px;background:#fff}a{color:var(--r);text-decoration:none;transition:all .2s}a:hover{color:#8a0000}.sf-topbar{background:var(--d);padding:8px 0;font-size:13px;color:#aaa}.sf-topbar-inner{max-width:1200px;margin:0 auto;padding:0 24px;display:flex;justify-content:flex-end;gap:20px}.sf-topbar a{color:#ccc}.sf-topbar a:hover{color:var(--r)}.sf-header{background:#fff;padding:10px 0;border-bottom:1px solid #eee;position:sticky;top:0;z-index:100;box-shadow:0 1px 8px rgba(0,0,0,.05)}.sf-header-inner{max-width:1200px;margin:0 auto;padding:0 24px;display:flex;align-items:center;justify-content:space-between;flex-wrap:wrap;gap:12px}.sf-logo img{height:48px}.sf-nav{display:flex;gap:2px}.sf-nav a{color:#333;font-size:13px;font-weight:500;padding:8px 12px;border-radius:4px;text-transform:uppercase;letter-spacing:.5px}.sf-nav a:hover,.sf-nav a.active{color:var(--r);background:rgba(188,0,0,.03)}.sf-hcta{background:var(--r);color:#fff!important;padding:9px 20px!important;border-radius:5px!important;font-weight:600!important}.sf-hcta:hover{background:#a00000!important}.sf-trust{display:flex;gap:8px}.sf-trust img{height:36px;opacity:.8}.sf-footer{background:var(--d);color:#888;padding:36px 0 20px;font-size:13px}.sf-footer-inner{max-width:1200px;margin:0 auto;padding:0 24px;display:grid;grid-template-columns:2fr 1fr 1fr;gap:36px}.sf-footer h4{color:#fff;font-size:13px;margin-bottom:12px;font-weight:600;text-transform:uppercase;letter-spacing:.8px}.sf-footer p{line-height:1.7}.sf-footer a{color:#aaa}.sf-footer a:hover{color:var(--r)}.sf-footer ul{list-style:none;padding:0}.sf-footer li{margin-bottom:6px}.sf-footer-bottom{max-width:1200px;margin:16px auto 0;padding:16px 24px 0;border-top:1px solid #2a2a2a;text-align:center;color:#555;font-size:12px}@media(max-width:960px){.sf-nav,.sf-trust{display:none}.sf-footer-inner{grid-template-columns:1fr}.sf-topbar-inner{justify-content:center}}`;
const HDR=`<div class="sf-topbar"><div class="sf-topbar-inner"><a href="mailto:${S.email}">${S.email}</a><a href="tel:02084227918">${S.phone}</a></div></div><header class="sf-header"><div class="sf-header-inner"><a href="${S.url}" class="sf-logo"><img src="${S.logo}" alt="SatFocus Security Solutions"></a><nav class="sf-nav"><a href="${S.url}">Home</a><a href="${S.url}/services-home-security-systems-av-and-security-solutions/">Services</a><a href="${IL.cctv}">CCTV</a><a href="${IL.alarms}">Alarms</a><a href="${IL.intercom}">Intercoms</a><a href="${S.url}/news/" class="active">News</a><a href="${IL.contact}" class="sf-hcta">Free Survey</a></nav><div class="sf-trust"><img src="${S.checkatrade}" alt="Checkatrade"><img src="${S.which}" alt="Which Trusted Trader"></div></div></header>`;
const FTR=`<footer class="sf-footer"><div class="sf-footer-inner"><div><h4>SatFocus Security Solutions</h4><p>Professional CCTV, alarm, intercom, and access control installation across London. Checkatrade & Which Trusted Trader approved.</p></div><div><h4>Quick Links</h4><ul><li><a href="${S.url}">Home</a></li><li><a href="${S.url}/services-home-security-systems-av-and-security-solutions/">Services</a></li><li><a href="${S.url}/news/">News</a></li><li><a href="${IL.locations}">Areas</a></li><li><a href="${IL.contact}">Contact</a></li></ul></div><div><h4>Get In Touch</h4><ul><li><a href="tel:02084227918">${S.phone}</a></li><li><a href="mailto:${S.email}">${S.email}</a></li><li>All London boroughs</li></ul></div></div><div class="sf-footer-bottom"><p>© ${new Date().getFullYear()} SatFocus Security Solutions</p></div></footer>`;

function postHTML(p){
const d=new Date(p.published_at*1000).toISOString().split('T')[0];
const df=new Date(p.published_at*1000).toLocaleDateString('en-GB',{day:'numeric',month:'long',year:'numeric'});
const m=Math.ceil((p.word_count||1500)/250);
// Clean NSI from content
let content=(p.content||'').replace(/As an NSI[- ]approved installer,?\s*/gi,'').replace(/NSI[- ]approved\s*/gi,'').replace(/NSI[- ]accredited\s*/gi,'').replace(/\bNSI\b/g,'');
return `<!DOCTYPE html><html lang="en-GB"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"><title>${esc(p.title)} | SatFocus Security Solutions</title><meta name="description" content="${esc(p.meta_description)}"><meta name="robots" content="index,follow,max-snippet:-1,max-image-preview:large"><link rel="canonical" href="${S.url}/news/${p.slug}/"><meta property="og:title" content="${esc(p.title)}"><meta property="og:description" content="${esc(p.meta_description)}"><meta property="og:type" content="article"><meta property="og:url" content="${S.url}/news/${p.slug}/"><script type="application/ld+json">[{"@context":"https://schema.org","@type":"Article","headline":${JSON.stringify(p.title)},"description":${JSON.stringify(p.meta_description)},"datePublished":"${d}","dateModified":"${d}","wordCount":${p.word_count||1500},"author":{"@type":"Organization","name":"SatFocus Security Solutions","url":"${S.url}"},"publisher":{"@type":"Organization","name":"SatFocus Security Solutions","url":"${S.url}","logo":{"@type":"ImageObject","url":"${S.logo}"},"telephone":"${S.phone}","areaServed":{"@type":"City","name":"London"}},"mainEntityOfPage":"${S.url}/news/${p.slug}/"},{"@context":"https://schema.org","@type":"BreadcrumbList","itemListElement":[{"@type":"ListItem","position":1,"name":"Home","item":"${S.url}"},{"@type":"ListItem","position":2,"name":"News","item":"${S.url}/news/"},{"@type":"ListItem","position":3,"name":"${esc(p.title)}"}]}]</script>
<style>${CSS}
.sf-hero{background:linear-gradient(135deg,#111,#222,#1a1a1a);padding:52px 0 44px;border-bottom:4px solid var(--r);position:relative;overflow:hidden}.sf-hero::before{content:'';position:absolute;top:0;right:0;width:40%;height:100%;background:linear-gradient(135deg,transparent,rgba(188,0,0,.06))}.sf-hero-inner{max-width:1200px;margin:0 auto;padding:0 24px;position:relative}.sf-bc{font-size:13px;color:#888;margin-bottom:16px}.sf-bc a{color:#aaa}.sf-bc a:hover{color:var(--r)}.sf-bc span{margin:0 6px;color:#555}.sf-hero h1{color:#fff;font-size:34px;font-weight:700;line-height:1.25;max-width:780px}.sf-hero-meta{margin-top:16px;display:flex;gap:16px;flex-wrap:wrap;align-items:center}.sf-hcat{background:var(--r);color:#fff;font-size:10px;font-weight:700;padding:4px 12px;border-radius:20px;text-transform:uppercase;letter-spacing:1px}.sf-hdate,.sf-hread{color:#999;font-size:13px}.sf-hread{background:rgba(255,255,255,.08);padding:3px 10px;border-radius:20px}
.sf-wrap{max-width:1200px;margin:0 auto;padding:0 24px;display:grid;grid-template-columns:1fr 320px;gap:48px}article{padding:40px 0 48px}article h2{font-size:24px;color:var(--d);margin:40px 0 16px;font-weight:700;line-height:1.3}article h3{font-size:19px;color:#444;margin:28px 0 12px;font-weight:600}article p{margin-bottom:18px;color:#444}article ul,article ol{margin:0 0 20px 20px;color:#444}article li{margin-bottom:8px}article strong{color:var(--d)}article a{font-weight:500;text-decoration:underline;text-decoration-color:rgba(188,0,0,.3);text-underline-offset:2px}article a:hover{text-decoration-color:var(--r)}
.sf-takeaways{background:linear-gradient(135deg,#f0f8f0,#f5faf5);border-left:4px solid #2E7D32;border-radius:0 10px 10px 0;padding:24px 28px;margin:28px 0 32px}.sf-takeaways h3{font-size:16px;color:#2E7D32;margin-bottom:12px;font-weight:700;text-transform:uppercase;letter-spacing:.5px}.sf-takeaways ul{margin:0;padding:0;list-style:none}.sf-takeaways li{padding:6px 0 6px 24px;position:relative;font-size:15px;line-height:1.5}.sf-takeaways li::before{content:'\\2713';position:absolute;left:0;color:#2E7D32;font-weight:700}
.sf-sidebar{padding:40px 0 48px}.sf-sbox{background:var(--l);border:1px solid var(--b);border-radius:10px;padding:24px;margin-bottom:20px}.sf-sbox h3{font-size:16px;margin-bottom:14px;color:var(--d);font-weight:700}.sf-sbox p{font-size:14px;color:#555;line-height:1.6;margin-bottom:10px}.sf-sbtn{display:block;background:var(--r);color:#fff;text-align:center;padding:12px;border-radius:6px;font-weight:600;font-size:14px;box-shadow:0 2px 8px rgba(188,0,0,.2);transition:all .2s}.sf-sbtn:hover{background:#a00000;color:#fff;transform:translateY(-1px)}.sf-svc{list-style:none;padding:0;margin:0}.sf-svc li{padding:8px 0;border-bottom:1px solid var(--b);font-size:13px}.sf-svc li:last-child{border-bottom:none}.sf-svc a{color:#444;display:flex;align-items:center;gap:8px;font-weight:500}.sf-svc a:hover{color:var(--r)}.sf-svc a::before{content:'\\25B8';color:var(--r);font-size:11px}.sf-brands{display:flex;flex-wrap:wrap;gap:6px;margin-top:8px}.sf-brand{background:#fff;border:1px solid var(--b);padding:3px 8px;border-radius:4px;font-size:11px;color:#555;font-weight:500}
.sf-faq{background:var(--l);border:1px solid var(--b);border-radius:10px;padding:28px;margin:36px 0}.sf-faq h2{margin-top:0;font-size:20px;border:none;padding:0}.sf-faq-item{border-bottom:1px solid #e0e0e0;padding:14px 0}.sf-faq-item:last-child{border-bottom:none;padding-bottom:0}.sf-faq-item h3{font-size:15px;margin:0 0 6px;color:var(--d);font-weight:600;border:none;padding:0}.sf-faq-item p{margin:0;font-size:14px;color:#555;line-height:1.6}
.sf-cta{background:linear-gradient(135deg,var(--d),#2a2a2a);color:#fff;padding:36px;border-radius:10px;margin:44px 0 0;text-align:center;position:relative;overflow:hidden}.sf-cta::before{content:'';position:absolute;top:0;right:0;width:30%;height:100%;background:linear-gradient(135deg,transparent,rgba(188,0,0,.08))}.sf-cta h3{color:#fff;font-size:22px;margin:0 0 8px;font-weight:700;border:none;padding:0;position:relative}.sf-cta p{margin:0 0 20px;color:#bbb;font-size:15px;position:relative}.sf-cta-btn{display:inline-block;background:var(--r);color:#fff;padding:13px 32px;border-radius:6px;font-weight:700;font-size:15px;box-shadow:0 4px 16px rgba(188,0,0,.3);transition:all .2s;position:relative}.sf-cta-btn:hover{background:#d40000;color:#fff;transform:translateY(-1px)}.sf-cta-sub{margin-top:12px;font-size:13px;color:#777;position:relative}.sf-cta-sub a{color:#eee;font-weight:600}
@media(max-width:960px){.sf-wrap{grid-template-columns:1fr;gap:0}.sf-sidebar{padding:0 0 40px}.sf-hero h1{font-size:26px}}
</style></head><body>${HDR}
<div class="sf-hero"><div class="sf-hero-inner"><div class="sf-bc"><a href="${S.url}">Home</a><span>›</span><a href="${S.url}/news/">News</a><span>›</span>${esc(p.title)}</div><h1>${esc(p.title)}</h1><div class="sf-hero-meta"><span class="sf-hcat">${esc(p.category||'Security')}</span><span class="sf-hdate">${df}</span><span class="sf-hread">${m} min read</span></div></div></div>
<div class="sf-wrap"><article>${content}
<div class="sf-cta"><h3>Protect Your Property Today</h3><p>Book a free security survey with our expert engineers across London.</p><a href="tel:02084227918" class="sf-cta-btn">Call ${S.phone}</a><p class="sf-cta-sub">or <a href="${IL.contact}">request a callback</a></p></div></article>
<aside class="sf-sidebar">
<div class="sf-sbox" style="background:linear-gradient(135deg,#1a1a1a,#2a2a2a);border-color:#333"><h3 style="color:#fff">Free Security Survey</h3><p style="color:#ccc">Our engineers assess your property and recommend the best solution — free.</p><a href="${IL.contact}" class="sf-sbtn">Book Free Survey</a></div>
<div class="sf-sbox"><h3>Our Services</h3><ul class="sf-svc"><li><a href="${IL.cctv}">CCTV Installation</a></li><li><a href="${IL.alarms}">Intruder Alarms</a></li><li><a href="${IL.intercom}">Video Intercoms</a></li><li><a href="${IL.service}">Alarm Servicing</a></li><li><a href="${IL.upgrade}">Alarm Upgrades</a></li><li><a href="${IL.locations}">Service Areas</a></li></ul></div>
<div class="sf-sbox"><h3>Brands We Install</h3><div class="sf-brands"><span class="sf-brand">Texecom</span><span class="sf-brand">Ajax</span><span class="sf-brand">Hikvision</span><span class="sf-brand">Dahua</span><span class="sf-brand">Pyronix</span><span class="sf-brand">Paxton</span><span class="sf-brand">BPT</span><span class="sf-brand">Videx</span><span class="sf-brand">Comelit</span><span class="sf-brand">Risco</span><span class="sf-brand">Visonic</span></div></div>
<div class="sf-sbox"><h3>Contact</h3><p style="font-size:13px;color:#555;margin:0"><strong>Phone:</strong> <a href="tel:02084227918">${S.phone}</a><br><strong>Email:</strong> <a href="mailto:${S.email}">${S.email}</a></p></div>
</aside></div>${FTR}</body></html>`}

function indexHTML(posts,cats){
const cc={'CCTV':'#1565C0','Intruder Alarms':'#BC0000','Video Intercoms':'#2E7D32','Access Control':'#6A1B9A','General Security':'#E65100','Local':'#00838F','Seasonal':'#EF6C00'};
const cards=posts.map(p=>{const d=new Date(p.published_at*1000).toLocaleDateString('en-GB',{day:'numeric',month:'long',year:'numeric'});const m=Math.ceil((p.word_count||1500)/250);const c=cc[p.category]||'#BC0000';return`<a href="${S.url}/news/${p.slug}/" class="sf-card"><div class="sf-card-top" style="background:linear-gradient(135deg,${c},${c}dd)"><span class="sf-card-cat">${esc(p.category||'Security')}</span></div><div class="sf-card-body"><h2>${esc(p.title)}</h2><p>${esc(p.excerpt||'').substring(0,150)}</p><div class="sf-card-meta"><span>${d}</span><span>${m} min</span></div></div></a>`}).join('\n');
return`<!DOCTYPE html><html lang="en-GB"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"><title>Security News & Guides | SatFocus Security Solutions London</title><meta name="description" content="Expert security guides, CCTV tips, alarm advice from SatFocus Security Solutions London."><meta name="robots" content="index,follow,max-snippet:-1,max-image-preview:large"><link rel="canonical" href="${S.url}/news/"><script type="application/ld+json">{"@context":"https://schema.org","@type":"Blog","name":"SatFocus Security News","url":"${S.url}/news/","publisher":{"@type":"Organization","name":"SatFocus Security Solutions","url":"${S.url}","logo":{"@type":"ImageObject","url":"${S.logo}"}}}</script>
<style>${CSS}body{background:#f4f4f4}
.sf-hero{background:linear-gradient(135deg,#111,#222,#1a1a1a);padding:48px 0 40px;border-bottom:4px solid var(--r);text-align:center;position:relative;overflow:hidden}.sf-hero::before{content:'';position:absolute;top:0;left:50%;transform:translateX(-50%);width:80%;height:100%;background:radial-gradient(ellipse,rgba(188,0,0,.05),transparent 70%)}.sf-hero h1{color:#fff;font-size:36px;font-weight:700;margin-bottom:10px;position:relative}.sf-hero p{color:#aaa;font-size:16px;max-width:580px;margin:0 auto;position:relative}.sf-hero-stats{display:flex;justify-content:center;gap:48px;margin-top:28px;position:relative}.sf-hero-stat{text-align:center}.sf-hero-stat strong{display:block;font-size:32px;color:var(--r);font-weight:800;line-height:1.2}.sf-hero-stat span{font-size:12px;color:#888;text-transform:uppercase;letter-spacing:1px}
.sf-page{max-width:1200px;margin:0 auto;padding:36px 24px 60px}.sf-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(340px,1fr));gap:24px}.sf-card{display:flex;flex-direction:column;background:#fff;border-radius:10px;overflow:hidden;color:var(--t);box-shadow:0 1px 3px rgba(0,0,0,.06);transition:all .3s}.sf-card:hover{box-shadow:0 12px 36px rgba(0,0,0,.1);transform:translateY(-4px)}.sf-card-top{padding:20px 24px;display:flex;align-items:center}.sf-card-cat{color:rgba(255,255,255,.9);font-size:10px;font-weight:700;text-transform:uppercase;letter-spacing:1px;background:rgba(0,0,0,.15);padding:3px 10px;border-radius:20px}.sf-card-body{padding:0 24px 24px;flex:1;display:flex;flex-direction:column}.sf-card h2{font-size:17px;line-height:1.4;margin-bottom:10px;font-weight:600;color:var(--d)}.sf-card p{font-size:13px;color:#666;flex:1;line-height:1.6;margin-bottom:14px}.sf-card-meta{display:flex;justify-content:space-between;font-size:11px;color:#999;padding-top:10px;border-top:1px solid #f0f0f0}.sf-card-meta span:last-child{background:#f5f5f5;padding:2px 8px;border-radius:10px}
@media(max-width:960px){.sf-grid{grid-template-columns:1fr}.sf-hero h1{font-size:28px}.sf-hero-stats{gap:24px}}
</style></head><body>${HDR}
<div class="sf-hero"><h1>Security News & Guides</h1><p>Expert advice from London's Checkatrade & Which Trusted Trader approved security installer.</p><div class="sf-hero-stats"><div class="sf-hero-stat"><strong>${posts.length}</strong><span>Articles</span></div><div class="sf-hero-stat"><strong>${cats.length}</strong><span>Categories</span></div><div class="sf-hero-stat"><strong>Free</strong><span>Surveys</span></div></div></div>
<div class="sf-page"><div class="sf-grid">${cards}</div></div>${FTR}</body></html>`}

async function main(){
let posts=db.prepare("SELECT * FROM sf_blog_posts WHERE status='published' ORDER BY published_at DESC").all();
if(REWRITE){console.log('Rewriting',posts.length,'posts via Claude API...\n');for(const p of posts){try{await rewritePost(p);await new Promise(r=>setTimeout(r,2000))}catch(e){console.log('  Failed:',p.keyword,e.message)}}posts=db.prepare("SELECT * FROM sf_blog_posts WHERE status='published' ORDER BY published_at DESC").all()}
console.log('\nGenerating HTML...\n');
posts.forEach(p=>{fs.writeFileSync(path.join(outputDir,p.slug+'.html'),postHTML(p),'utf8');console.log('  ✅',p.title)});
const cats=[...new Set(posts.map(p=>p.category).filter(Boolean))];
fs.writeFileSync(path.join(outputDir,'index.html'),indexHTML(posts,cats),'utf8');console.log('\n  ✅ Index');
fs.writeFileSync(path.join(outputDir,'news-sitemap.xml'),(()=>{const t=new Date().toISOString().split('T')[0];let x='<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n  <url><loc>'+S.url+'/news/</loc><lastmod>'+t+'</lastmod><changefreq>daily</changefreq><priority>0.8</priority></url>\n';posts.forEach(p=>{x+='  <url><loc>'+S.url+'/news/'+p.slug+'/</loc><lastmod>'+new Date(p.published_at*1000).toISOString().split('T')[0]+'</lastmod><changefreq>monthly</changefreq><priority>0.7</priority></url>\n'});return x+'</urlset>'})(),'utf8');console.log('  ✅ Sitemap');
fs.writeFileSync(path.join(outputDir,'.htaccess'),'RewriteEngine On\nRewriteBase /news/\nRewriteCond %{REQUEST_FILENAME} -d\nRewriteRule ^(.+[^/])$ /news/$1/ [R=301,L]\nRewriteCond %{REQUEST_FILENAME} -f\nRewriteRule ^ - [L]\nRewriteCond %{REQUEST_FILENAME} -d\nRewriteRule ^ - [L]\n','utf8');
const kp='/root/.ssh/satfocus_krystal_rsa',rm='/home/aismarts/satfocussecurity.co.uk/news',h='aismarts@tajfun-lon.krystal.uk';
console.log('\nUploading...');
try{execSync(`ssh -p 722 -i ${kp} -o StrictHostKeyChecking=no ${h} "mkdir -p ${rm}"`,{stdio:'pipe'});posts.forEach(p=>{execSync(`ssh -p 722 -i ${kp} -o StrictHostKeyChecking=no ${h} "mkdir -p ${rm}/${p.slug}"`,{stdio:'pipe'})});let b=`put ${outputDir}/index.html ${rm}/index.html\nput ${outputDir}/news-sitemap.xml ${rm}/news-sitemap.xml\nput ${outputDir}/.htaccess ${rm}/.htaccess\n`;posts.forEach(p=>{b+=`put ${outputDir}/${p.slug}.html ${rm}/${p.slug}/index.html\n`});fs.writeFileSync(path.join(outputDir,'sftp-batch.txt'),b);execSync(`sftp -P 722 -i ${kp} -o StrictHostKeyChecking=no -b ${outputDir}/sftp-batch.txt ${h}`,{stdio:'pipe'});console.log('  ✅ Done!\n\nView:',S.url+'/news/')}catch(e){console.error('Upload failed:',e.message)}}
main().catch(e=>{console.error('Fatal:',e);process.exit(1)});
